### ISSUE TITLE
TA Meeting - Oct 28th 2024

### ISSUE THREAD

**Issue by parishanizam** [parishanizam/TeleHealth#161]
**Purpose of Meeting**

**October 28th 2024**

**Attendance**

- [x] Promish Kandel
- [x] Parisha Nizam
- [x] Jasmine Sun-Hu
- [x] Mitchell Weingust

**Questions to Ask**

- Section 3.3 Design Verification Plan - What does this entail, not a lot of information given. What is it, and what do we need to include in documents

- What is Area Testing in Section 4 - is this part of the system or area of the requirement

- Section 4.1 Do we make tests for every functional requirement or "area" subsection of functional requirements

- Symbolic Contraints - How do we come up with these without being unnecessary

- The prof mentioned in class that we dont need to fill in section 5 unit testing, do we need to make that clear/write something in the report

 - What is MIS, when do we complete this?

**Comment by jasminesunhu** [comment]
1. (3.3) Answer "How will the different pieces of our project be verified?" The design document is due in January, how will you verify that? One suggestion is asking for peer feedback or creating a checklist (which can be put in the appendix). "Do all our design decisions trace back to a requirement?". Use the rubric, but it is also up to the group's standards as well.
2. (4.1) Each requirement should be covered by a test, at least one test should be traced back to every requirement but that doesn't necessarily mean each requirement needs a test written for it, a test can cover multiple requirements. Some tests may be manual, some may be automated (for our project more tests will probably be manual). 
3. (Symbolic constants) Avoid putting random numbers (e.g. 42) in our program without context, symbolic constants is just giving a value a name because it may be reused throughout the document. It makes the document more maintainable if numbers need to be searched/changed for any reason

**Comment by mitcholll** [comment]
each requirement should be covered by min. 1 test
some can be covered by automated, don't have to go in detail but do need to describe them
many tests will be manual
instead of worrying about how to interface with a camera, use zoom api, get recording from zoom (assuming you can do that with the api call)

for nfr, usability, etc., need other types of instruments like surveys, focus group, meeting, interview, give it to a medical professional, ask them to do a speech assessment
don't delay decisions. include the actual survey (a draft) in the appendix, in the requirements you can say "survey q3 should have an average score of 4/5" for usability

area testing: may have 3-4 broad features, each of those might have multiple requirements related to it (ex. administering the speech assessment), the broad strokes of different features we'll have. under that have the different tests that will test 1 or more tests of that area

Section 5: "We will fill in this part of the document by XX date (before rev0)"
def. before the v&v report is due in February

Avoid using 'magic numbers', give it a name, a constant
Makes document more maintainable (change 80 to 90 later on)

POC: November 11th
balance it so the rev0 demo is near the end
better to have more time for then
Last deliverable of the semster
make sure to implement early!!
