### ISSUE TITLE
TA Meeting - Monday October 7th 3:45pm

### ISSUE THREAD

**Issue by PromishKandel** [parishanizam/TeleHealth#94]
**Purpose of Meeting**
To review srs document and ask questions 
**Date and Time**
Monday October 7th 3:45
Team 22
![image](https://github.com/user-attachments/assets/d2d3f4fb-7143-4e93-9410-366e91ca175b)
**Attendance**

- [x] Promish Kandel
- [x] Parisha Nizam
- [x] Jasmine Sun-Hu
- [x] Mitchell Weingust

**Questions to Ask**

- For the scope of work section (6) I see that in previous years other groups had made diagrams, is that required? Confused on what this section brings to the document. 

- what does work partitioning mean? section 6.3

- What is the difference between BUC and PUC? section 6.4 and 8.3

- For the purpose of the project, I see that previous years other groups also put purpose of the document too. Is this standard for this section, and something we should do? Also do we break up this section to purpose of the section and purpose of the document or could we put it in one?

**Comment by mitcholll** [comment]
- 2.6 - Priorities assigned to users: should this be a ranked order, or do we state "Primary, Secondary, Tertiary" users?
- 7.2 - Data Dictionary, what goes into a data dictionary? What is necessary?
- 8 - The Scope of the Product - What are the expectations for this section? Is a use case diagram required? Are the individual product use cases supposed to be an in-depth description for each use case?

**Comment by jasminesunhu** [comment]
(3) what is meant by off the shelf software and enterprise constraints? are they are applicable to our project?
(9-17) formal specification recommendation? data collection, web interface, data processing, or something else?

Quick clarification questions:
(20) is new problems just brainstorming potential issues that will occur after product is released?
(24) our plan is to include a tutorial on the webpage, is that considered user documentation/ training?
(25) is waiting room for future ideas?
(26) is ideas for solution just solution brainstorming?

**Comment by parishanizam** [comment]
Show current Data model and dictionary - ask if we are on the right path

**Comment by PromishKandel** [comment]
Order:
- (9-17) formal specification recommendation? data collection, web interface, data processing, or something else?
- What is the difference between BUC and PUC? section 6.4 and 8.3
- Show current Data model and dictionary - ask if we are on the right path
- What the difference between the use case diagram and use case table
- 2.6 - Priorities assigned to users: should this be a ranked order, or do we state "Primary, Secondary, Tertiary" users?
- For the purpose of the project, I see that previous years other groups also put purpose of the document too. Is this standard for this section, and something we should do? Also do we break up this section to purpose of the section and purpose of the document or could we put it in one?
- (3) what is meant by off the shelf software and enterprise constraints? are they are applicable to our project?

**Comment by mitcholll** [comment]
- Do a FSM instead of discrete math at this point
- 6.4
- 8.1: Make the diagram, 8.2: Table, 8.3: List all the use cases and give details, give preconditions, postconditions, explanations (refer to examples), give each of them numbers, give FR-7 is related to UC (use-case) 2
- 8.1: Product Boundary: How it's related to other things, and what things are not relevant
- 8.2: Table (numbers and names, a quick overview) Diagram
- 8.3: Description
- Data model and dictionary -> too specific to add now. Really for groups where you're working with an example/model you currently have.

**Comment by jasminesunhu** [comment]
TA Meeting Notes
1. can use FSM instead of formal specification, refer to LO_SpecMath rubric on avenue
2. TA expects too see the the 3ra3 actor stick figure type use case, make sure to enumerate them so they can be referenced (UC1, UC2). the traceability matrix will link use cases to functional requirements. don't have to do 6.4 if it doesn't apply to our project
3. too specific towards design, can be used later but skip adding it for the requirements
4. do diagram + descriptions, table can just be the use case number + names. product boundary is more for if our system interacts with other systems
